module.exports = {
    success: [
      { message: "You polished Lucifer's horns.", souls: [50, 150] },
      { message: "You helped a lost soul find its way... to the wrong circle.", souls: [75, 175] },
      { message: "You collected tolls on the River Styx.", souls: [100, 200] },
      { message: "You filed demonic paperwork. It was hellishly boring, but it paid.", souls: [120, 220] },
      { message: "You organized a soul auction and took a commission.", souls: [80, 180] },
      { message: "You worked the night shift at a demon possession call center.", souls: [90, 190] },
      { message: "You delivered brimstone packages to various circles of hell.", souls: [60, 160] },
      { message: "You maintained the furnaces in the Third Circle.", souls: [110, 210] },
      { message: "You served drinks at a damned souls tavern.", souls: [70, 170] },
      { message: "You trained new imps in proper torment techniques.", souls: [130, 230] },
      { message: "You worked as a tour guide for newly arrived sinners.", souls: [85, 185] },
      { message: "You sharpened pitchforks for the demon army.", souls: [95, 195] },
    ],
    rare: [
      { message: "You successfully pranked a rival demon lord and made off with a hefty bag of souls!", souls: [500, 1000] },
      { message: "You discovered a hidden cache of souls in a forgotten corner of the underworld.", souls: [750, 1250] },
      { message: "You won big at the hellish casino's soul slots!", souls: [600, 1100] },
      { message: "You blackmailed a corrupt angel and they paid handsomely to keep quiet.", souls: [800, 1300] },
      { message: "You found and returned Satan's lost pet Cerberus. The reward was substantial!", souls: [900, 1400] },
      { message: "You intercepted a shipment of blessed artifacts and sold them on the black market.", souls: [700, 1200] },
    ],
    fail: [
      { message: "You tried to sell ice water in the frozen Ninth Circle. It didn't go well.", souls: [-25, -10] },
      { message: "A hellhound stole your wallet.", souls: [-50, -20] },
      { message: "You accidentally insulted a high-ranking demon and had to pay a fine.", souls: [-40, -15] },
      { message: "You got caught slacking on the job and were docked pay.", souls: [-35, -5] },
      { message: "You fell into a pit of lava and had to pay for medical expenses.", souls: [-60, -25] },
      { message: "You bet on the wrong demon in the underworld fighting pits.", souls: [-45, -10] },
      { message: "A group of troublesome imps pranked you and made off with your earnings.", souls: [-30, -5] },
      { message: "You accidentally broke some expensive torture equipment.", souls: [-55, -20] },
    ],
}; 