name: Node.js CI

on:
  push:
    branches: [ "master" ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - run: git pull origin main
    - run: pm2 restart src/main.js
    - run: echo "updated code from hit"
