name: Node.js CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2
      - name: Pull changes
        run: |
          cd ../../../../hellbot
          git reset --hard
          git pull origin main
      - name: Install dependencies
        run: npm install
      - name: Restart PM2
        run: pm2 restart hellbot
      - name: Get commit message
        run: echo "COMMIT_MESSAGE=$(git log -1 --pretty=format:'%s')" >> $GITHUB_ENV
      - name: Send bot updated message
        run: node -e "require('./src/commands/botupdated').execute(process.env.COMMIT_MESSAGE)"
        env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
          COMMIT_MESSAGE: ${{ env.COMMIT_MESSAGE }}

