name: Node.js CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2
      - name: Pull changes
        run: git pull origin main
      - name: Install dependencies
        run: npm install
      - name: Restart PM2
        run: pm2 restart default
      - name: Send bot updated message
        run: node -e "require('./src/commands/botupdated').execute()" 
        env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
