name: Node.js CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2
      - name: cd to hellbot
        run: cd hellbot
      - name: Pull changes
        run: git pull origin main
      - name: Install dependencies
        run: npm install
      - name: Restart PM2
        run: pm2 restart src/main.js
      - name: Log update
        run: echo "Updated code from Git" >> ./hook_log.txt
