name: Node.js CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2
      - name: Pull changes
        run: git pull origin main
      - name: Install dependencies
        run: npm install
      - name: Restart PM2
        run: pm2 restart hellbot
      - name: Get commit message
        id: get_commit
        run: echo "::set-output name=commit_message::$(git log -1 --pretty=format:'%s')
      - name: Send bot updated message
        run: node -e "require('./src/commands/botupdated').execute(process.env.COMMIT_MESSAGE)"
        env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
          COMMIT_MESSAGE: ${{ steps.get_commit.outputs.commit_message }}

